Unset version: '3.9' 
services: 
  db: 
    image: mysql:8.0 
    container_name: mi-mysql 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=usuario_app
      - MYSQL_PASSWORD=password 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
    
  volumes: 
    db_data: