server:
  port: 8089
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: usuario_app
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: UTC

logging:
  config: classpath:log4j2.xml

  



